-- Add down migration script here

DROP TABLE IF EXISTS sensor_permissions;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS roles;

ALTER TABLE sensor ADD COLUMN IF NOT EXISTS publisher VARCHAR(255) NOT NULL DEFAULT '*';
ALTER TABLE sensor ADD COLUMN IF NOT EXISTS consumer VARCHAR(255) NOT NULL DEFAULT '*';

ALTER TABLE sensor DROP COLUMN IF EXISTS owner;

ALTER TABLE users ADD COLUMN IF NOT EXISTS role VARCHAR(50) NOT NULL DEFAULT 'user';
